# Reading Result Dimensions
READING_RESULT_DIMENSION_2 = '2'
READING_RESULT_DIMENSION_6 = '6'
READING_RESULT_DIMENSION_8 = '8'
READING_RESULT_DIMENSION_49 = '49'

READING_RESULT_DIMENSIONS = [
    READING_RESULT_DIMENSION_2,
    READING_RESULT_DIMENSION_6,
    READING_RESULT_DIMENSION_8,
    READING_RESULT_DIMENSION_49
]

# Reading Result Frequencies
READING_RESULT_FREQUENCY_DAILY = 'daily'
READING_RESULT_FREQUENCY_WEEKLY = 'weekly'
READING_RESULT_FREQUENCY_MORNING = 'morning'
READING_RESULT_FREQUENCY_AFTERNOON = 'afternoon'
READING_RESULT_FREQUENCY_EVENING = 'evening'
READING_RESULT_FREQUENCY_TIMELESS = 'timeless'

READING_RESULT_FREQUENCIES = [
    READING_RESULT_FREQUENCY_DAILY,
    READING_RESULT_FREQUENCY_WEEKLY,
    READING_RESULT_FREQUENCY_MORNING,
    READING_RESULT_FREQUENCY_AFTERNOON,
    READING_RESULT_FREQUENCY_EVENING,
    READING_RESULT_FREQUENCY_TIMELESS
]

# Reading Result Types
READING_RESULT_TYPE_GENERAL = 'general'
READING_RESULT_TYPE_ELEMENTAL = 'elemental'
READING_RESULT_TYPE_CARDINAL = 'cardinal'

READING_RESULT_TYPES = [
    READING_RESULT_TYPE_GENERAL,
    READING_RESULT_TYPE_ELEMENTAL,
    READING_RESULT_TYPE_CARDINAL
]

# Hexagram Line Yarrow Values
HEXAGRAM_LINE_YARROW_VALUE_6 = '6'
HEXAGRAM_LINE_YARROW_VALUE_9 = '9'

HEXAGRAM_YARROW_VALUES = [
    HEXAGRAM_LINE_YARROW_VALUE_6,
    HEXAGRAM_LINE_YARROW_VALUE_9
]

# Hexagram Line Types
HEXAGRAM_LINE_TYPE_REMINDER = 'reminder'
HEXAGRAM_LINE_TYPE_WARNING = 'warning'

HEXAGRAM_LINE_TYPES = [
    HEXAGRAM_LINE_TYPE_REMINDER,
    HEXAGRAM_LINE_TYPE_WARNING
]

# Hexagram Line Numbers
HEXAGRAM_LINE_NUMBER_1 = 1
HEXAGRAM_LINE_NUMBER_2 = 2
HEXAGRAM_LINE_NUMBER_3 = 3
HEXAGRAM_LINE_NUMBER_4 = 4
HEXAGRAM_LINE_NUMBER_5 = 5
HEXAGRAM_LINE_NUMBER_6 = 6

HEXAGRAM_LINE_NUMBERS = [
    HEXAGRAM_LINE_NUMBER_1,
    HEXAGRAM_LINE_NUMBER_2,
    HEXAGRAM_LINE_NUMBER_3,
    HEXAGRAM_LINE_NUMBER_4,
    HEXAGRAM_LINE_NUMBER_5,
    HEXAGRAM_LINE_NUMBER_6
]

# Result Line Values
RESULT_LINE_VALUE_6 = 6
RESULT_LINE_VALUE_7 = 7
RESULT_LINE_VALUE_8 = 8
RESULT_LINE_VALUE_9 = 9

RESULT_LINE_VALUES = [
    RESULT_LINE_VALUE_6,
    RESULT_LINE_VALUE_7,
    RESULT_LINE_VALUE_8,
    RESULT_LINE_VALUE_9
]