commands: {}
domain:
  entities: {}
  factories: {}
  models:
    hexagram:
      class_name: Hexagram
      dependencies:
      - class_name: HexagramLine
        model_id: hexagram_line
        module: null
      name: Hexagram
      properties:
      - description: "the name of the hexagram"
        name: name
        required: true
        type: str
      - inner_type: str
        name: secondary_names
        required: false
        type: list
      - description: traditional order numbering of the hexagram
        name: wilhelm_index
        required: true
        type: int
      - description: the yarrow-based unique identifier of the hexagram
        name: yarrow_value
        required: true
        type: str
      - description: the translated judgement of the hexagram
        inner_type: str
        name: judgement
        required: false
        type: list
      - description: the translated image of the hexagram
        inner_type: str
        name: image
        required: false
        type: list
      - description: the changing lines in the hexagram
        inner_type: value_object
        inner_type_model_id: hexagram_line
        name: changing_lines
        required: false
        type: list
      type: value_object
    hexagram_line:
      class_name: HexagramLine
      dependencies: []
      name: Hexagram Line
      properties: []
      test: null
      type: value_object
    result_line:
      class_name: ResultLine
      dependencies: []
      name: Result Line
      properties:
      - description: the hexagram line position for the reading result
        name: position
        required: true
        type: int
      - name: heaven_line
        required: true
        type: int
      - name: man_line
        required: true
        type: int
      - name: earth_line
        required: true
        type: int
      - choices:
        - '6'
        - '7'
        - '8'
        - '9'
        name: line_value
        required: true
        type: int
      type: value_object
  modules: {}
  repos: {}
errors: {}
features:
  groups:
    reading:
      features:
        new:
          functions:
          - data_mapping: add_new_reading
            function_path: reading.add_new_reading
interfaces:
  types:
    cli:
      commands:
        reading:
          subcommands:
            new:
              arguments:
              - choices:
                - '2'
                - '6'
                - '8'
                - '49'
                help: reading dimension
                name_or_flags:
                - --dimension
                - -d
                required: true
              - help: reading input
                name_or_flags:
                - --input
                - -i
                nargs: +
                required: true
              - help: name of the reading
                name_or_flags:
                - name
              help: add new reading
              name: Add New I-Ching Reading
      parent_arguments: []
