commands: {}
domain:
  entities: {}
  factories: {}
  modules: {}
  repos: {}
  value_objects:
    hexagram:
      class_name: Hexagram
      name: Hexagram
      properties: []
    result_line:
      class_name: ResultLine
      name: Result Line
      properties:
      - description: the hexagram line position for the reading result
        name: position
        required: true
        type: int
      - name: heaven_line
        required: true
        type: int
      - name: man_line
        required: true
        type: int
      - name: earth_line
        required: true
        type: int
      - choices:
        - '6'
        - '7'
        - '8'
        - '9'
        name: line_value
        required: true
        type: int
errors: {}
features:
  groups:
    reading:
      features:
        new:
          functions:
          - data_mapping: add_new_reading
            function_path: reading.add_new_reading
interfaces:
  types:
    cli:
      commands:
        reading:
          subcommands:
            new:
              arguments:
              - choices:
                - '2'
                - '6'
                - '8'
                - '49'
                help: reading dimension
                name_or_flags:
                - --dimension
                - -d
                required: true
              - help: reading input
                name_or_flags:
                - --input
                - -i
                nargs: +
                required: true
              - help: name of the reading
                name_or_flags:
                - name
              help: add new reading
              name: Add New I-Ching Reading
      parent_arguments: []