commands: {}
domain:
  constants:
    READING_RESULT_DIMENSIONS:
      type: list
      inner_type: str
      value:
      - '2'
      - '2.1'
      - '2.2'
      - '6'
      - '8'
      - '49'
  factories: {}
  objects:
    hexagram:
      class_name: Hexagram
      dependencies:
      - class_name: HexagramLine
        model_id: hexagram_line
        module: null
      module: readings
      name: Hexagram
      properties:
      - description: the name of the hexagram
        name: name
        required: true
        type: str
      - inner_type: str
        name: secondary_names
        required: false
        type: list
      - description: traditional order numbering of the hexagram
        name: wilhelm_index
        required: true
        type: int
      - description: the yarrow-based unique identifier of the hexagram
        name: yarrow_value
        required: true
        type: str
      - description: the translated judgement of the hexagram
        inner_type: str
        name: judgement
        required: false
        type: list
      - description: the translated image of the hexagram
        inner_type: str
        name: image
        required: false
        type: list
      - description: the changing lines in the hexagram
        inner_type: model
        inner_type_model_id: hexagram_line
        name: changing_lines
        required: false
        type: list
      type: value_object
    hexagram_line:
      class_name: HexagramLine
      dependencies: []
      name: Hexagram Line
      properties:
      - description: the translated changing line text
        inner_type: str
        name: text
        required: false
        type: list
      - choices:
        - reminder
        - warning
        description: the changing line type
        name: type
        required: false
        type: str
      - choices:
        - '6'
        - '9'
        description: the yarrow value of the changing line
        name: yarrow_value
        required: false
        type: int
      - choices:
        - '1'
        - '2'
        - '3'
        - '4'
        - '5'
        - '6'
        description: the number order the changing line
        name: line_number
        required: false
        type: int
      type: value_object
    hexagram_result:
      base_type_model_id: null
      class_name: HexagramResult
      dependencies: []
      name: Hexagram Result
      properties:
      - description: name of the resulting hexagram
        name: name
        required: true
        type: str
      - description: number of the resulting hexagram
        name: wilhelm_index
        required: true
        type: int
      type: value_object
    reading_result:
      base_type_model_id: null
      class_name: ReadingResult
      dependencies:
      - class_name: ResultLine
        dependency_type: property
        model_id: result_line
        module: null
      - class_name: HexagramResult
        dependency_type: property
        model_id: hexagram_result
        module: null
      name: Reading Result
      properties:
      - description: name of the I-Ching reading
        name: name
        required: true
        type: str
      - choices:
        - '2'
        - '6'
        - '8'
        - '49'
        description: dimension number for result line calculation
        name: dimension
        required: true
        type: str
      - choices:
        - daily
        - weekly
        - morning
        - afternoon
        - evening
        default: daily
        description: the periodic frequency that applies to the reading result
        name: frequency
        type: str
      - choices:
        - general
        - elemental
        - cardinal
        default: general
        description: the type of reading
        name: type
        type: str
      - description: the date of reading
        name: date
        required: true
        type: date
      - description: the input lines of reading
        inner_type: model
        inner_type_model_id: result_line
        name: result_lines
        type: list
      - description: the previous or current hexagram result
        inner_type: hexagram_result
        name: current_or_previous
        type: model
      - description: the next hexagram result
        inner_type: hexagram_result
        name: next
        type: model
      type: entity
    result_line:
      class_name: ResultLine
      dependencies: []
      name: Result Line
      properties:
      - description: the hexagram line position for the reading result
        name: position
        required: true
        type: int
      - name: heaven_line
        required: true
        type: int
      - name: man_line
        required: true
        type: int
      - name: earth_line
        required: true
        type: int
      - choices:
        - '6'
        - '7'
        - '8'
        - '9'
        name: line_value
        required: true
        type: int
      type: value_object
  modules:
    readings:
      name: Readings
      description: Contains domain model objects for I-Ching readings.
      direct_import: false
  repos: {}
errors: 
  INVALID_REQUEST_DATA:
    error_code: '000000001'
    message:
      en_US: 'Invalid request contains the following errors: {}'
features:
  groups:
    reading:
      features:
        new:
          functions:
          - data_mapping: add_new_reading
            function_path: reading.new
          - data_mapping: print_new_reading_result
            function_path: printing.reading
        add_results:
          functions:
          - data_mapping: add_reading_results
            function_path: reading.add_results
        sync:
          functions:
          - data_mapping: default
            function_path: reading.sync
            params:
              request_type: SyncReading
interfaces:
  types:
    cli:
      commands:
        reading:
          subcommands:
            new:
              arguments:
              - choices:
                - '2'
                - '2.1'
                - '2.2'
                - '6'
                - '8'
                - '49'
                help: reading dimension
                name_or_flags:
                - --dimension
                - -d
              - help: reading input
                name_or_flags:
                - --input
                - -i
                nargs: +
              - choices:
                - standard
                - json
                help: the type of input
                name_or_flags:
                - --input-type
                type: str
              - help: name of the reading
                name_or_flags:
                - name
              - help: date of reading (defaults to today)
                name_or_flags:
                - --date
                type: str
              - choices:
                - daily
                - weekly
                - morning
                - afternoon
                - evening
                default: daily
                help: time period of reading
                name_or_flags:
                - --frequency
                type: str
              - choices:
                - general
                - elemental
                - cardinal
                default: general
                help: type of reading
                name_or_flags:
                - --type
                type: str
              - help: upload file path for reading entry
                name_or_flags:
                - --upload-file
                type: str
              - help: removes the uploaded reading file
                name_or_flags:
                - --remove-file
                - -r
                type: bool
                action: store_true
              - help: save only to cache
                name_or_flags:
                - --cache-only
                type: bool
                action: store_true
              - help: add reading with no result input
                name_or_flags:
                - --no-input
                type: bool
                action: store_true
              help: add new reading
              name: Add New I-Ching Reading
            get:
              arguments:
              - help: reading id
                name_or_flags:
                - reading_id
                type: str
              - help: print the output as json
                name_or_flags:
                - --to-json
                type: bool
                action: store_true
              help: get reading data
              name: Get Reading Data
            add_results:
              arguments:
              - help: reading id
                name_or_flags:
                - reading_id
                type: str
              - help: result input
                name_or_flags:
                - --input
                - -i
                nargs: +
              - choices:
                - standard
                - json
                help: the type of input
                name_or_flags:
                - --input-type
                type: str
            sync:
              arguments:
              - help: sync reading data
                name_or_flags:
                - reading_id
                type: str
              - help: upload file path for reading entry
                name_or_flags:
                - --upload-file
                type: str
              - help: removes the cached reading data
                name_or_flags:
                - --remove-from-cache
                - -r
                type: bool
                action: store_true
              help: sync reading data
              name: Sync Reading Data
      parent_arguments: []
