commands: {}
domain:
  entities: {}
  factories: {}
  modules: {}
  repos: {}
  value_objects: {}
errors: {}
features:
  groups: {}
interfaces:
  types:
    cli:
      commands:
        readings:
          subcommands:
            new:
              arguments:
              - choices:
                - '2'
                - '6'
                - '8'
                - '49'
                help: reading dimensions
                name_or_flags:
                - --dimensions
                - -d
                required: true
              - help: reading input
                name_or_flags:
                - --input
                - -i
                nargs: '18'
                required: true
              help: add new reading
              name: Add New I-Ching Reading
